[2024-08-12 00:37:25,385: INFO: main: This is an example logging]
[2024-08-12 02:38:38,271: INFO: main: This is an example logging]
[2021-01-01 04:57:43,200: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 04:57:43,211: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 05:01:57,732: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 05:01:57,743: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 05:01:57,751: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 05:01:57,758: INFO: common: Created directory at: artifacts]
[2021-01-01 05:13:17,673: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 05:13:17,716: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 05:13:17,737: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 05:13:17,746: INFO: common: Created directory at: artifacts]
[2024-08-15 19:29:47,648: INFO: main: >>>>> Stage Data ingestion has started <<<<<]
[2024-08-15 19:29:47,678: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2024-08-15 19:29:47,689: INFO: common: Yaml file : params.yaml loaded successfully]
[2024-08-15 19:29:47,698: INFO: common: Yaml file : schema.yaml loaded successfully]
[2024-08-15 19:29:47,701: INFO: common: Created directory at: artifacts]
[2024-08-15 19:29:47,702: INFO: common: Created directory at: artifacts/data_ingestion]
[2024-08-15 19:32:01,347: INFO: main: >>>>> Stage Data ingestion has started <<<<<]
[2024-08-15 19:32:01,385: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2024-08-15 19:32:01,391: INFO: common: Yaml file : params.yaml loaded successfully]
[2024-08-15 19:32:01,467: INFO: common: Yaml file : schema.yaml loaded successfully]
[2024-08-15 19:32:01,473: INFO: common: Created directory at: artifacts]
[2024-08-15 19:32:01,474: INFO: common: Created directory at: artifacts/data_ingestion]
[2021-01-01 02:15:08,966: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 02:15:08,977: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 02:15:08,996: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 02:15:09,003: INFO: common: Created directory at: artifacts]
[2021-01-01 02:15:09,019: INFO: common: Created directory at: artifacts/data_transformation]
[2021-01-01 02:15:12,142: INFO: 3665554176: Data splitted into test and training set]
[2021-01-01 02:15:12,147: INFO: 3665554176: (7500, 9)]
[2021-01-01 02:15:12,172: INFO: 3665554176: (2500, 9)]
[2024-08-16 04:03:17,725: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2024-08-16 04:03:17,731: INFO: common: Yaml file : params.yaml loaded successfully]
[2024-08-16 04:03:17,759: INFO: common: Yaml file : schema.yaml loaded successfully]
[2024-08-16 04:03:17,764: INFO: common: Created directory at: artifacts]
[2024-08-16 04:03:17,765: INFO: common: Created directory at: artifacts/data_validation]
[2024-08-16 04:03:25,686: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2024-08-16 04:03:25,690: INFO: common: Yaml file : params.yaml loaded successfully]
[2024-08-16 04:03:25,698: INFO: common: Yaml file : schema.yaml loaded successfully]
[2024-08-16 04:03:25,699: INFO: common: Created directory at: artifacts]
[2024-08-16 04:03:25,700: INFO: common: Created directory at: artifacts/data_transformation]
[2024-08-16 04:03:26,744: INFO: data_transformation: Data splitted into test and training set]
[2024-08-16 04:03:26,745: INFO: data_transformation: (7500, 9)]
[2024-08-16 04:03:26,746: INFO: data_transformation: (2500, 9)]
[2024-08-16 04:03:26,764: INFO: main: >>>>> Stage Data ingestion has started <<<<<]
[2024-08-16 04:03:26,875: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2024-08-16 04:03:26,883: INFO: common: Yaml file : params.yaml loaded successfully]
[2024-08-16 04:03:26,903: INFO: common: Yaml file : schema.yaml loaded successfully]
[2024-08-16 04:03:26,907: INFO: common: Created directory at: artifacts]
[2024-08-16 04:03:26,909: INFO: common: Created directory at: artifacts/data_ingestion]
[2024-08-16 04:03:28,013: ERROR: main: HTTP Error 400: Bad Request]
Traceback (most recent call last):
  File "/Users/ntchindagiscard/Documents/end-end-mlflow/main.py", line 11, in <module>
    obj.main()
  File "/Users/ntchindagiscard/Documents/end-end-mlflow/src/mlProject/pipeline/stage_01_data_ingestion.py", line 20, in main
    data_ingestion.download_file()
  File "/Users/ntchindagiscard/Documents/end-end-mlflow/src/mlProject/components/data_ingestion.py", line 31, in download_file
    _, headers = request.urlretrieve(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
[2021-01-01 02:40:18,628: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 02:40:18,654: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 02:40:18,681: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 02:40:18,687: INFO: common: Created directory at: artifacts]
[2021-01-01 02:40:18,700: INFO: common: Created directory at: artifacts/model_trainer]
[2021-01-01 02:41:04,784: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 02:41:04,798: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 02:41:04,824: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 02:41:04,834: INFO: common: Created directory at: artifacts]
[2021-01-01 02:41:04,848: INFO: common: Created directory at: artifacts/model_trainer]
[2021-01-01 02:42:45,789: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 02:42:45,848: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 02:42:45,869: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 02:42:45,878: INFO: common: Created directory at: artifacts]
[2021-01-01 02:42:45,889: INFO: common: Created directory at: artifacts/model_trainer]
[2021-01-01 02:44:21,814: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 02:44:21,824: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 02:44:21,839: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 02:44:21,844: INFO: common: Created directory at: artifacts]
[2021-01-01 02:44:21,848: INFO: common: Created directory at: artifacts/model_trainer]
[2021-01-01 02:47:05,922: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 02:47:05,948: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 02:47:05,973: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 02:47:05,986: INFO: common: Created directory at: artifacts]
[2021-01-01 02:47:05,995: INFO: common: Created directory at: artifacts/model_trainer]
[2021-01-01 02:49:08,421: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 02:49:08,432: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 02:49:08,451: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 02:49:08,455: INFO: common: Created directory at: artifacts]
[2021-01-01 02:49:08,462: INFO: common: Created directory at: artifacts/model_trainer]
[2021-01-01 02:49:50,384: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 02:49:50,396: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 02:49:50,411: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 02:49:50,418: INFO: common: Created directory at: artifacts]
[2021-01-01 02:49:50,424: INFO: common: Created directory at: artifacts/model_trainer]
[2021-01-01 02:50:07,547: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 02:50:07,557: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 02:50:07,577: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 02:50:07,586: INFO: common: Created directory at: artifacts]
[2021-01-01 02:50:07,591: INFO: common: Created directory at: artifacts/model_trainer]
[2021-01-01 03:29:39,583: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 03:29:39,586: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 03:29:39,594: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 03:29:39,595: INFO: common: Created directory at: artifacts]
[2021-01-01 03:29:39,597: INFO: common: Created directory at: artifacts/data_validation]
[2021-01-01 03:29:43,827: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 03:29:43,830: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 03:29:43,836: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 03:29:43,838: INFO: common: Created directory at: artifacts]
[2021-01-01 03:29:43,839: INFO: common: Created directory at: artifacts/data_transformation]
[2021-01-01 03:29:44,861: INFO: data_transformation: Data splitted into test and training set]
[2021-01-01 03:29:44,861: INFO: data_transformation: (7500, 9)]
[2021-01-01 03:29:44,862: INFO: data_transformation: (2500, 9)]
[2021-01-01 03:29:45,229: INFO: main: >>>>> Stage Data ingestion has started <<<<<]
[2021-01-01 03:29:45,247: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 03:29:45,252: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 03:29:45,259: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 03:29:45,260: INFO: common: Created directory at: artifacts]
[2021-01-01 03:29:45,263: INFO: common: Created directory at: artifacts/data_ingestion]
[2021-01-01 03:29:45,695: ERROR: main: <urlopen error [Errno 8] nodename nor servname provided, or not known>]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ntchindagiscard/Documents/end-end-mlflow/main.py", line 12, in <module>
    obj.main()
  File "/Users/ntchindagiscard/Documents/end-end-mlflow/src/mlProject/pipeline/stage_01_data_ingestion.py", line 20, in main
    data_ingestion.download_file()
  File "/Users/ntchindagiscard/Documents/end-end-mlflow/src/mlProject/components/data_ingestion.py", line 31, in download_file
    _, headers = request.urlretrieve(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
[2021-01-01 03:29:45,757: INFO: main: >>>> Data validation stage started <<<<< ]
[2021-01-01 03:29:45,758: INFO: main: >>>> Data validation stage completed 

x=========x]
[2021-01-01 03:29:45,759: INFO: main: >>>> Data transformation stage started <<<<< ]
[2021-01-01 03:29:45,760: INFO: main: >>>> Data transformation stage completed 

x=========x]
[2021-01-01 03:29:45,764: INFO: main: >>>>> Stage Data transformation has started <<<<<]
[2021-01-01 03:29:45,802: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 03:29:45,813: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 03:29:45,877: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 03:29:45,880: INFO: common: Created directory at: artifacts]
[2021-01-01 03:29:45,883: INFO: common: Created directory at: artifacts/model_trainer]
[2021-01-01 03:29:46,417: INFO: main: >>>>> Stage Data transformation has completed 

 x=========x]
[2021-01-01 03:31:12,309: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 03:31:12,314: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 03:31:12,321: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 03:31:12,323: INFO: common: Created directory at: artifacts]
[2021-01-01 03:31:12,323: INFO: common: Created directory at: artifacts/data_validation]
[2021-01-01 03:31:16,377: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 03:31:16,380: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 03:31:16,386: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 03:31:16,387: INFO: common: Created directory at: artifacts]
[2021-01-01 03:31:16,388: INFO: common: Created directory at: artifacts/data_transformation]
[2021-01-01 03:31:17,370: INFO: data_transformation: Data splitted into test and training set]
[2021-01-01 03:31:17,371: INFO: data_transformation: (7500, 9)]
[2021-01-01 03:31:17,372: INFO: data_transformation: (2500, 9)]
[2021-01-01 03:31:17,611: INFO: main: >>>>> Stage Data ingestion has started <<<<<]
[2021-01-01 03:31:17,625: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 03:31:17,628: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 03:31:17,637: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 03:31:17,638: INFO: common: Created directory at: artifacts]
[2021-01-01 03:31:17,638: INFO: common: Created directory at: artifacts/data_ingestion]
[2021-01-01 03:31:17,822: ERROR: main: <urlopen error [Errno 8] nodename nor servname provided, or not known>]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ntchindagiscard/Documents/end-end-mlflow/main.py", line 12, in <module>
    obj.main()
  File "/Users/ntchindagiscard/Documents/end-end-mlflow/src/mlProject/pipeline/stage_01_data_ingestion.py", line 20, in main
    data_ingestion.download_file()
  File "/Users/ntchindagiscard/Documents/end-end-mlflow/src/mlProject/components/data_ingestion.py", line 31, in download_file
    _, headers = request.urlretrieve(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
[2021-01-01 03:31:17,842: INFO: main: >>>> Data validation stage started <<<<< ]
[2021-01-01 03:31:17,843: INFO: main: >>>> Data validation stage completed 

x=========x]
[2021-01-01 03:31:17,843: INFO: main: >>>> Data transformation stage started <<<<< ]
[2021-01-01 03:31:17,843: INFO: main: >>>> Data transformation stage completed 

x=========x]
[2021-01-01 03:31:17,843: INFO: main: >>>>> Stage Model trainer has started <<<<<]
[2021-01-01 03:31:17,877: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 03:31:17,881: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 03:31:17,891: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 03:31:17,892: INFO: common: Created directory at: artifacts]
[2021-01-01 03:31:17,893: INFO: common: Created directory at: artifacts/model_trainer]
[2021-01-01 03:31:18,324: INFO: main: >>>>> Stage Model trainer has completed 

 x=========x]
[2021-01-01 13:14:44,658: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 13:14:44,665: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 13:14:44,674: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 13:14:44,678: INFO: common: Created directory at: artifacts]
[2021-01-01 13:14:44,680: INFO: common: Created directory at: artifacts/data_validation]
[2021-01-01 13:14:48,496: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 13:14:48,503: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 13:14:48,516: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 13:14:48,517: INFO: common: Created directory at: artifacts]
[2021-01-01 13:14:48,518: INFO: common: Created directory at: artifacts/data_transformation]
[2021-01-01 13:14:49,291: INFO: data_transformation: Data splitted into test and training set]
[2021-01-01 13:14:49,292: INFO: data_transformation: (7500, 9)]
[2021-01-01 13:14:49,292: INFO: data_transformation: (2500, 9)]
[2021-01-01 13:14:49,560: INFO: main: >>>>> Stage Data ingestion has started <<<<<]
[2021-01-01 13:14:49,575: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 13:14:49,579: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 13:14:49,585: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 13:14:49,587: INFO: common: Created directory at: artifacts]
[2021-01-01 13:14:49,588: INFO: common: Created directory at: artifacts/data_ingestion]
[2021-01-01 13:14:49,765: ERROR: main: <urlopen error [Errno 8] nodename nor servname provided, or not known>]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ntchindagiscard/Documents/end-end-mlflow/main.py", line 12, in <module>
    obj.main()
  File "/Users/ntchindagiscard/Documents/end-end-mlflow/src/mlProject/pipeline/stage_01_data_ingestion.py", line 20, in main
    data_ingestion.download_file()
  File "/Users/ntchindagiscard/Documents/end-end-mlflow/src/mlProject/components/data_ingestion.py", line 31, in download_file
    _, headers = request.urlretrieve(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
[2021-01-01 13:14:49,790: INFO: main: >>>> Data validation stage started <<<<< ]
[2021-01-01 13:14:49,791: INFO: main: >>>> Data validation stage completed 

x=========x]
[2021-01-01 13:14:49,792: INFO: main: >>>> Data transformation stage started <<<<< ]
[2021-01-01 13:14:49,792: INFO: main: >>>> Data transformation stage completed 

x=========x]
[2021-01-01 13:14:49,792: INFO: main: >>>>> Stage Model trainer has started <<<<<]
[2021-01-01 13:14:49,818: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2021-01-01 13:14:49,828: INFO: common: Yaml file : params.yaml loaded successfully]
[2021-01-01 13:14:49,837: INFO: common: Yaml file : schema.yaml loaded successfully]
[2021-01-01 13:14:49,839: INFO: common: Created directory at: artifacts]
[2021-01-01 13:14:49,840: INFO: common: Created directory at: artifacts/model_trainer]
[2021-01-01 13:14:50,227: INFO: main: >>>>> Stage Model trainer has completed 

 x=========x]
[2024-08-18 22:45:05,761: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2024-08-18 22:45:05,780: INFO: common: Yaml file : params.yaml loaded successfully]
[2024-08-18 22:45:05,798: INFO: common: Yaml file : schema.yaml loaded successfully]
[2024-08-18 22:45:05,812: INFO: common: Created directory at: artifacts]
[2024-08-18 22:45:05,834: INFO: common: Created directory at: artifacts/model_evaluation]
[2024-08-19 04:50:26,196: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2024-08-19 04:50:26,232: INFO: common: Yaml file : params.yaml loaded successfully]
[2024-08-19 04:50:26,276: INFO: common: Yaml file : schema.yaml loaded successfully]
[2024-08-19 04:50:26,304: INFO: common: Created directory at: artifacts]
[2024-08-19 04:50:26,314: INFO: common: Created directory at: artifacts/model_evaluation]
[2024-08-19 06:05:18,097: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2024-08-19 06:05:18,162: INFO: common: Yaml file : params.yaml loaded successfully]
[2024-08-19 06:05:18,200: INFO: common: Yaml file : schema.yaml loaded successfully]
[2024-08-19 06:05:18,232: INFO: common: Created directory at: artifacts]
[2024-08-19 06:05:18,255: INFO: common: Created directory at: artifacts/model_evaluation]
[2024-08-19 06:05:22,568: INFO: common: Json file saved at: artifacts/model_evaluation/metrics.json]
[2024-08-19 06:07:32,123: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2024-08-19 06:07:32,145: INFO: common: Yaml file : params.yaml loaded successfully]
[2024-08-19 06:07:32,163: INFO: common: Yaml file : schema.yaml loaded successfully]
[2024-08-19 06:07:32,176: INFO: common: Created directory at: artifacts]
[2024-08-19 06:07:32,186: INFO: common: Created directory at: artifacts/model_evaluation]
[2024-08-19 06:07:32,885: INFO: common: Json file saved at: artifacts/model_evaluation/metrics.json]
[2024-08-19 06:09:59,382: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2024-08-19 06:09:59,436: INFO: common: Yaml file : params.yaml loaded successfully]
[2024-08-19 06:09:59,471: INFO: common: Yaml file : schema.yaml loaded successfully]
[2024-08-19 06:09:59,479: INFO: common: Created directory at: artifacts]
[2024-08-19 06:09:59,500: INFO: common: Created directory at: artifacts/model_evaluation]
[2024-08-19 06:10:06,315: INFO: common: Json file saved at: artifacts/model_evaluation/metrics.json]
[2024-08-19 06:12:11,543: INFO: common: Yaml file : config/config.yaml loaded successfully]
[2024-08-19 06:12:11,566: INFO: common: Yaml file : params.yaml loaded successfully]
[2024-08-19 06:12:11,634: INFO: common: Yaml file : schema.yaml loaded successfully]
[2024-08-19 06:12:11,646: INFO: common: Created directory at: artifacts]
[2024-08-19 06:12:11,693: INFO: common: Created directory at: artifacts/model_evaluation]
[2024-08-19 06:12:12,499: INFO: common: Json file saved at: artifacts/model_evaluation/metrics.json]
